"""init

Revision ID: bafc71b3b304
Revises: cd29f815773b
Create Date: 2024-05-31 12:10:18.362843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafc71b3b304'
down_revision: Union[str, None] = 'cd29f815773b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('recomendado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_descripcion'), 'items', ['descripcion'], unique=False)
    op.create_index(op.f('ix_items_nombre'), 'items', ['nombre'], unique=False)
    op.create_index(op.f('ix_items_recomendado'), 'items', ['recomendado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_recomendado'), table_name='items')
    op.drop_index(op.f('ix_items_nombre'), table_name='items')
    op.drop_index(op.f('ix_items_descripcion'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
